# Generated by Django 4.2 on 2023-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='duration_hour',
        ),
        migrations.RemoveField(
            model_name='category',
            name='duration_minute',
        ),
        migrations.RemoveField(
            model_name='category',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='category',
            name='durations_days',
        ),
        migrations.AddField(
            model_name='category',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
