# Generated by Django 4.2 on 2023-10-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_category_duration_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_course',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
    ]
