# Generated by Django 4.2 on 2023-10-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sub_course_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_course',
            name='extra_details',
            field=models.CharField(default='', max_length=30),
        ),
    ]
