# Generated by Django 4.2 on 2023-10-04 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_sub_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_subtopics',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.defaulttopic'),
        ),
    ]
