# Generated by Django 4.2 on 2023-10-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userselected_sub_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselected_sub',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sub_course'),
        ),
    ]
