# Generated by Django 4.2 on 2023-10-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_sub_course_extra_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_topic',
            name='extra_details',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
