# Generated by Django 5.0.3 on 2024-03-20 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_sub_course_extra_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('SubTopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sub_topic')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sub_course')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('show_format', models.CharField(choices=[('text', 'Text'), ('code', 'Code'), ('image', 'Image')], max_length=5)),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.documentation')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
