# Generated by Django 5.0.3 on 2024-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_topic_name_documentation_documentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documentation_images/'),
        ),
    ]
