# Generated by Django 5.0.3 on 2024-03-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_documentationdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationdata',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
